# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cd4dbf13f0872e92dea75b784df6ffc9c5754f40a7cd4e460672b540509ef2722c1f96eec609af573a15581eb7e5dc1f0116c588de12b4dc5592bc63ad4e1c9

test:
  secret_key_base: 4a2bc9c52fad17f0736dc8abdea734fcc96d428048a5bbc3892ecdca6c1c0970933f97e87f7639e50423db9bf0bce32d6cacaafc1c8229cdc4ae2032d9579dec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
